services:
  mariadb:
    init: true
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    healthcheck:
        test: ["CMD", "mysql", "-u", "${DOCKER_USR_SQL}", "-p${DOCKER_PASS_SQL}", "-e", "SELECT 1"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3
    # healthcheck da aggiungere

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/usr/share/wordpress
    restart: on-failure
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/usr/share/wordpress
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/jfranco/wordpress
        #/home/jfranco
        # ✘ Container mariadb       Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/srcs_mariadb/_data': failed to mount local volume: mount /home/lilith/inception/srcs/home/jfranco/mariadb:/var/lib/docker/volumes/srcs_mariadb/_data, flags: 0x1000: no such file or directory


  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/jfranco/mariadb

networks:
  inception:
    driver: bridge

