
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    # healthcheck da aggiungere

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/usr/share/wordpress
    restart: on-failure
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/usr/share/wordpress
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: volume/wordpress
        #/home/jfranco


  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: volume/mariadb

networks:
  inception:
    driver: bridge

